### ISSUE TITLE
Players are being disconnected unknown meta type 16

### ISSUE THREAD

**Issue by krisjenner** [PaperMC/Waterfall#329] opened 2018-12-15 15:01 UTC
https://gist.github.com/krisjenner/c86e7cfb2ae83cfbb21714dcf2f06e44

**Comment by krisjenner** [comment] 2018-12-15 15:01
just happens at random intervals

**Comment by krisjenner** [comment] 2018-12-15 15:04
connecting to sponge modded server

**Comment by electronicboy** [comment] 2018-12-15 15:10
Duplicate of #136

**Closed by electronicboy** 2018-12-15 15:10 UTC
