### ISSUE TITLE
Team x already exists in this scoreboard

### ISSUE THREAD

**Issue by GiansCode** [PaperMC/Waterfall#496] opened 2020-05-01 12:16 UTC
We're running a multi proxy setup, and, today, out of the blue, the following [issue](https://hastebin.com/hotabequgu.cs) started occurring on our SkyBlock servers, and we're not exactly sure how to deal with it.

Steps we've taken, in order, have been

- Stopping the server(s)
- Deleting the "scoreboard.dat" file from the main world on all server(s)
- Restarting the server(s)
- Manually removing the team(s) causing issues (they come back quick)
- Temporarily removing Scoreboard, and Nametag plugins (and also the Disguise one, since it had a Team)

We're running the latest build of Waterfall, and, if it helps, our Bukkit servers run the latest build of Tuinity (I'll get the version numbers when I get back to my PC)

**Comment by Janmm14** [comment] 2020-05-01 15:57
Which plugins do you use on your servers for scoreboards?
Can you modify them easily so no server has identical internal scoreboard names?

I think a possible cause of this happening is on server switch when target server wants to define a scoreboard with the same internal name as the previous server one was on.

**Comment by GiansCode** [comment] 2020-05-01 15:59
We use FeatherBoard as the main scoreboard, but, other plugins like NametagEdit, and LibsDisguises also modify/create boards

I could look into renaming them. But, it's just weird how it came out of nowhere

**Comment by electronicboy** [comment] 2020-05-01 17:30
duplicate of #318

**Closed as completed by electronicboy** 2020-05-01 17:30 UTC
