### ISSUE TITLE
disconnected with: Exception Connecting:BadPacketException : Unexpected packet received during server connector process!

### ISSUE THREAD

**Issue by rares1337** [PaperMC/Waterfall#618] opened 2021-03-13 12:15 UTC
Hello!
I am using Waterfall 1.16 but whenever i try to join i get this error
disconnected with: Exception Connecting:BadPacketException : Unexpected packet received during server connector process!
my config
```
server_connect_timeout: 5000
listeners:
- query_port: 25565
  host: 0.0.0.0:25565
  motd: 'no lol'
  max_players: 1
  force_default_server: false
  tab_size: 60
  forced_hosts:
    pvp.md-5.net: pvp
  tab_list: GLOBAL_PING
  bind_local_address: true
  ping_passthrough: false
  query_enabled: false
  proxy_protocol: false
  priorities:
  - auth
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: fed6e8e1-0aa8-4466-995f-bf3120e576e3
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  auth:
    motd: '&1Just another Waterfall - Forced Host'
    address: localhost:9999
    restricted: false

**Comment by Chew** [comment] 2021-03-13 19:30
Partial Duplicate of https://github.com/PaperMC/Waterfall/issues/605.

If you need further assistance, we'd be happy to help you on [Discord in #waterfall-help](https://discord.gg/papermc).

**Closed as completed by Chew** 2021-03-13 19:30 UTC
