### ISSUE TITLE
Maybe cause IndexOutOfBoundsException

### ISSUE THREAD

**Issue by khlfkk** [PaperMC/Waterfall#214] opened 2018-03-04 17:55 UTC
just to share the error, thanks.

```io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:

	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 6941, widx: 17408, cap: 32768))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:39) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:cb4db00:168]
	... 29 more```

**Comment by jamierocks** [comment] 2018-03-04 20:51
In future could you post the whole stacktrace (there should be one or more lines at the start) - however this issue has come up numerous times and is a duplicate of https://github.com/WaterfallMC/Waterfall/issues/178.

**Closed as completed by jamierocks** 2018-03-04 20:51 UTC
