### ISSUE TITLE
Seeing several issues on connections...

### ISSUE THREAD

**Issue by Kainzo** [PaperMC/Waterfall#270] opened 2018-08-02 01:49 UTC
https://paste2.org/k9Vbn8cC

**Comment by LoXR** [comment] 2018-08-02 03:09
Getting that aswell, https://pastebin.com/Hd1QS8fK
Using the latest ViaVersion dev build if it could be due to that.

**Comment by electronicboy** [comment] 2018-08-02 12:11
Duplicate of #264

**Closed as completed by electronicboy** 2018-08-02 12:11 UTC
