### ISSUE TITLE
Unexpected packet received during server login process!

### ISSUE THREAD

**Issue by DJDanTheMan** [PaperMC/Waterfall#606] opened 2021-02-06 23:39 UTC
Hi, 
I'm using Waterfall version git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395. However, when I try to login to one particular server which is my skyblock server I get this error on the proxy. 
[18:32:20] [Netty Worker IO Thread #2/INFO]: [_DJDan] <-> ServerConnector [skyblock] has connected
[18:32:20] [Netty Worker IO Thread #2/ERROR]: [_DJDan <-> ServerConnector [skyblock] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
1b82017b227472616e736c617465223a.
 
Is it possible to fix this? I can't seem to replicate it on my own private server so I don't know how I can resolve this issue.

**Comment by Chew** [comment] 2021-02-07 01:55
Duplicate of #605 (your issue?) Feel free to hop into [#waterfall-help on Discord](https://discord.gg/papermc) if you need more help.

**Closed as completed by Chew** 2021-02-07 01:55 UTC
Labels: resolution: duplicate
