### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GameModeOnX** [PaperMC/Waterfall#243] opened 2018-07-06 12:43 UTC
https://hasteb.in/zekuzogi.lua
how to fix it?

**Comment by jamierocks** [comment] 2018-07-06 13:53
This is a duplicate of #178. There isn't a proper fix, though you could look into applying #187 to your build. @electronicboy has looked into the issue far more than myself ;)

**Closed as completed by jamierocks** 2018-07-06 13:53 UTC
Labels: resolution: duplicate

**Comment by Black-Hole** [comment] 2018-07-06 15:06
And the issue was already reported at https://github.com/SpigotMC/BungeeCord/issues/2446 with some hints.
