### ISSUE TITLE
Byte buff error

### ISSUE THREAD

**Issue by zachschrier** [PaperMC/Waterfall#160] opened 2017-07-26 01:09 UTC
This error is triggered when joining a lobby in the proxy console on the latest version of waterfall. 

https://hastebin.com/esavixurot.lua

Please fix ASAP

**Comment by kashike** [comment] 2017-07-26 01:37
This is not an exception, it is only a warning message.

**Comment by kashike** [comment] 2017-07-26 01:37
Duplicate of #74.
Duplicate of #126.

**Closed as completed by kashike** 2017-07-26 01:37 UTC
Labels: resolution: duplicate, resolution: invalid

**Comment by jamierocks** [comment] 2017-07-26 01:38
The `Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!` "issue" is *not actually an issue*, rather a change in procedure from how BungeeCord previously handled things. (see #126)
