### ISSUE TITLE
Waterfall + SpongeForge 1.12.2

### ISSUE THREAD

**Issue by ben21121** [PaperMC/Waterfall#516] opened 2020-06-10 10:31 UTC
Hello,

I’m having issues with my servers after enabling IP Forwarding so that i can use multichat, when i try to join through my Waterfall server i start connecting to my main modpack server add see some fml authentication in its console but then i’m kicked just after it said i joined the game, the client gives me the error
“The server you where previously on went down, you have been connected to a fallback server”

And in the Waterfall console i get
“DownstreamBridge <-> [main] - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.EntityEffect 79 Protocol GAME Direction TO_CLIENT”

In the waterfall config and each sponge server config i have all the forwarding settings correct,
Could someone provide me with a patched version of BungeeCord? Or SpongePIs as i saw that fixed issues on an old forum post but not sure if there is support for 1.12.2, just need something to make this work as i’m not skilled at writing Java.
Much appreciated

**Comment by electronicboy** [comment] 2020-06-10 10:31
Duplicate of #418

**Closed as completed by electronicboy** 2020-06-10 10:31 UTC

**Comment by ben21121** [comment] 2020-06-10 10:47
I see you tagged in a duplicate issue but could not see a fix, what would i need to do solve the issue for my servers? I have them all running without IP Forwarding so players can get on but they cannot cross server talk, is there anything i can reconfigure?

**Comment by electronicboy** [comment] 2020-06-10 10:48
The linked issue is open for a reason, there is no current fix yet, bar tryna work out which mod is breaking it

**Comment by ben21121** [comment] 2020-06-10 11:02
Sorry i'm new to github, is there any more information you need? i can upload logs or files if needed
