### ISSUE TITLE
Unexpected packet received during server login process!

### ISSUE THREAD

**Issue by ygtdmn** [PaperMC/Waterfall#281] opened 2018-08-30 12:25 UTC
```
[15:23:29 ERROR]: [test|/0.0.0.0:53075] <-> ServerConnector [Lobby1] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
4103
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:157) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:45f9076:215]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

I'm using latest Waterfall and lately i'm having this errors in my console a lot. Are these bad? If they are not can i or you remove it?

**Comment by electronicboy** [comment] 2018-08-30 12:40
Duplicate of #264

**Closed as completed by electronicboy** 2018-08-30 12:40 UTC
