### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by successed** [PaperMC/Waterfall#355] opened 2019-03-02 21:17 UTC
[00:13:28 ERROR]: [/37.26.130.72:42528] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 01005090
[00:13:28 ERROR]: [/37.26.130.72:43038] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 010050b9
[00:13:28 ERROR]: [/37.26.130.72:43604] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 01005090
[00:13:28 ERROR]: [/37.26.130.72:44044] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4f4e4e45435420776562312e73747261
[00:13:28 ERROR]: [/37.26.130.72:44614] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4f4e4e4543542077656263616d312e73
[00:13:28 ERROR]: [/37.26.130.72:45330] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4f4e4e45435420722e77656263616d30
[00:13:29 ERROR]: [/37.26.130.72:45672] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 455420687474703a2f2f686964656661
[00:13:29 ERROR]: [/37.26.130.72:46220] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 455420687474703a2f2f7777772e6672
[00:13:29 ERROR]: [/37.26.130.72:46828] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 455420687474703a2f2f667265657072
[00:13:29 ERROR]: [/37.26.130.72:47260] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 01005000
[00:13:29 ERROR]: [/37.26.130.72:47646] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 01005000
[00:13:29 ERROR]: [/37.26.130.72:48276] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 01005000

**Comment by successed** [comment] 2019-03-02 21:18
http://prntscr.com/msdzy5

**Comment by electronicboy** [comment] 2019-03-02 21:24
Duplicate of #264

**Closed as completed by electronicboy** 2019-03-02 21:24 UTC
Labels: resolution: duplicate
