### ISSUE TITLE
Waterfall and Forge 1.16.5 (Mohist, or forge server) are not compatible

### ISSUE THREAD

**Issue by Ellinikor** [PaperMC/Waterfall#616] opened 2021-03-02 08:17 UTC
Error when logging in the server by wayf of the waterfall: 

This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.

Except that, mods are present on the client with forge 1.16.5 (3306).

ip-forwarding true with forge true in the config.yml in waterfall config.
On the forge server (I use Mohist 1.16.5) there are bungeccord: true in spigot.yml and in the bungee.yml : connexion-throttles = -1.

**Comment by electronicboy** [comment] 2021-03-02 08:18
Duplicate of #450

**Closed as completed by electronicboy** 2021-03-02 08:18 UTC
