### ISSUE TITLE
You have been kicked to the fallback server when both servers are still online

### ISSUE THREAD

**Issue by xlGaM3r** [PaperMC/Waterfall#343] opened 2019-01-27 15:07 UTC
Sooo ppl just get random Fallback server messages when the server just works perfectly fine 

`[15:48:51 ERROR]: [/93.161.98.27:55985|Twisted_Wrath] <-> DownstreamBridge <-> [Ozone3] - encountered exception
java.lang.IllegalArgumentException: Unknown meta type 14
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:236) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:129) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:152) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:95) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:131) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:112) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ca93ae9:245]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[15:48:51 INFO]: [Twisted_Wrath] disconnected with: The server you were previously on went down, you have been connected to a fallback server
`

**Comment by electronicboy** [comment] 2019-01-27 21:42
Duplicate of #136

**Closed as completed by electronicboy** 2019-01-27 21:42 UTC
