### ISSUE TITLE
The server received an incomplete label set. Please contact the server administrator

### ISSUE THREAD

**Issue by vlssu** [PaperMC/Waterfall#635] opened 2021-04-30 16:03 UTC
I am using the 1.16.5 mod server to enter the server, and the title appears. I tried to turn off the login server and it didn’t work. Forge_support: true also didn’t work, so the problem should be in waterfall. I am using waterfall-1.16-414.
![image](https://user-images.githubusercontent.com/43847794/116722130-9e7b2000-aa10-11eb-9081-ca421153cf78.png)

**Comment by electronicboy** [comment] 2021-04-30 16:04
Duplicate of #450

**Closed as completed by electronicboy** 2021-04-30 16:04 UTC
