### ISSUE TITLE
Issues with scoreboard (help)

### ISSUE THREAD

**Issue by JHarris12345** [PaperMC/Waterfall#430] opened 2019-11-02 03:23 UTC
I get this error quite a bit which has crashed my server. I am not sure what the fix is, I am VERY new to console errors like this https://pastebin.com/BvDCGpdu

**Comment by electronicboy** [comment] 2019-11-02 03:25
Duplicate of #318 
Only "fix" is to ensure that servers will have unique team names (Plugins will need to consider bungee setups properly, basically), this is basically a bungeecord issue

**Closed as completed by electronicboy** 2019-11-02 03:25 UTC

**Comment by JHarris12345** [comment] 2019-11-02 03:27
@electronicboy Can you give a bit more of a dummed down version to a newbie please. How do I ensure servers have unique team names? Also how do I make sure plugins consider bungee setups properly?

**Comment by electronicboy** [comment] 2019-11-02 03:28
You would need to speak to the plugin authors of whatever is using scoreboards on your servers to prevent these collisions, there is no real easy fix here, plugins basically need to take steps to avoid this

**Comment by JHarris12345** [comment] 2019-11-02 03:30
How do I know what plugins use scoreboards? Also so there is nothing I can do to fix this? I can only rely on devs? @electronicboy
