### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by FunnyCraft** [PaperMC/Waterfall#12] opened 2016-06-05 11:48 UTC
http://pastebin.com/2NCLhAwd

**Comment by Janmm14** [comment] 2016-06-05 20:33
`05.06 14:33:33 [Multicraft] Skipped 37 lines due to rate limit (30/s)`
According to this, the log you showed does not contain the full error. Please look into the log files and give us the full error.

**Comment by FunnyCraft** [comment] 2016-06-06 11:20
http://pastebin.com/qBHGez7e

**Comment by Janmm14** [comment] 2016-06-06 14:56
Originally duplicate of https://github.com/WaterfallMC/Waterfall-Old/issues/74
Issue apparently not fixed in https://github.com/WaterfallMC/Waterfall/commit/2187ad029ca9b2bf00a2e8e8ab52a74b9cecb6ad although it was tried.
The issue is:
`java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick`

**Comment by kamcio96** [comment] 2016-06-06 15:16
@FunnyCraft can you test that jar?
 https://github.com/WaterfallMC/Waterfall/pull/15

**Comment by Techcable** [comment] 2016-06-06 16:05
Here is @Sitmobedaf 's log
http://mc.kanet.ru/proxy.log

**Edit 1:** reposted [as github gist](https://gist.github.com/anonymous/2b130f81c9eedc4998852dea7f650aa5)

**Comment by Janmm14** [comment] 2016-06-06 17:53
We should alter the error message and output information about the state.

**Comment by Janmm14** [comment] 2016-06-06 17:55
Please update your Waterfall to the latest build and give the error again, it should now be in this format: 
`Cannot get ID for packet <packet> in state <state>`

**Comment by FunnyCraft** [comment] 2016-06-06 18:29
http://pastebin.com/XAVu0dJ4
https://ci.getwaterfall.xyz/viewLog.html?buildTypeId=Waterfall_Build&buildId=lastSuccessful&buildBranch=master&tab=artifacts this download last build?

**Comment by Techcable** [comment] 2016-06-06 18:32
@FunnyCraft 
Oh great, @DemonWav 's CI isn't setup to automatically build.
Grab the actual latest from [our alternate CI](https://ci.aquifermc.org/job/Waterfall/).

**Comment by FunnyCraft** [comment] 2016-06-06 18:51
why not used this patch https://github.com/WaterfallMC/Waterfall/pull/15/commits/78341871955b284b0723b16668b0fbae6d021424 for a fix?

**Comment by kamcio96** [comment] 2016-06-06 18:55
Just test, we want be sure thats problem ;)

**Comment by FunnyCraft** [comment] 2016-06-06 18:58
http://pastebin.com/ntz1x26D

**Comment by Janmm14** [comment] 2016-06-06 19:22
Ah its the Handshake state. As the client is normally sending handshake and the following loginrequest together without wait time (why should it wait), there should be no reason to not change the handshake state to the login state or allow the kick packet in the handshake state as the client is never really in a handshake state (does it even exist client-side?).

**Comment by Techcable** [comment] 2016-06-06 19:26
@Janmm14 The handshake state is a perfectly valid part of the protocol, however it doesn't have a kick packet (the only one that does have a kick packet is PLAY and LOGIN)

**Closed as completed** 2016-06-06 19:40 UTC

**Comment by Techcable** [comment] 2016-06-06 19:41
Reopen/comment if the issue isn't fixed. Make sure to use the build from [the alternative CI](https://ci.aquifermc.org/job/Waterfall/), since commits currently aren't triggering builds on DemonWav 's CI.
